#!/usr/bin/env python3

# CLI for the UMI checker thingy
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter

import umi_checker.umi_checker

def parse_args():
    a = ArgumentParser( description = "UMI checking with lossy counting",
                        formatter_class = ArgumentDefaultsHelpFormatter )

    a.add_argument("--exact", action="store_true",
                   help="Use an exact counter, not a lossy one")
    a.add_argument("--offset", type=int,
                   help="Take the UMI from this base (counting from 0)")
    a.add_argument("--length", type=int,
                   help="Length of the UMI, if not the whole sequence")
    a.add_argument("fqfile", nargs=1,
                   help="File of sequences to scan")

    a.add_argument("--debug", "--verbose", action="store_true",
                   help="Show debugging infos")

    return a.parse_args()

if __name__ == "__main__":
    umi_checker.umi_checker.main(parse_args())
