#!/bin/bash

# Wrapper to run the preferred version of fastq_screen with the preferred
# selection of databases and configuration.
# Note  that we expect the conf file to define databases only!
# Note2 that the newer version of fastq_scrren neither accepts nor expects
# a --seqcount parameter, and the subsample size will be approximate.

# Caller should set --threads and --subset 1000000 (or whatever)

export PATH="/lustre/software/bowtie/bowtie-1.2.1.1:$PATH"

exec /lustre/software/fastq_screen/fastq_screen_v0.11.3/fastq_screen \
    --aligner bowtie
    --conf /lustre/references/fastqscreen/fastq_screen.conf_bowtie1_20171122 \
    --quiet --bowtie '--trim3 100' \
    "$@"
