#!/bin/bash

# Bootstrap a new VEnv in ./_illuminatus_venv suitable for running Illuminatus.
# This seemed easier than using setup.py but maybe I just lack imagination.

# As of illuminatus 1.5 this will also install Snakemake as part of the VEnv.

if [[ "$0" == "$BASH_SOURCE" ]] ; then
    echo "You need to source this file, not run it."
    exit 1
fi

activate_venv() {
    #We need to ensure -u is not set but then put the old value back.
    local reset=`set +o | grep -w nounset` ; set +o nounset
    source ./_illuminatus_venv/bin/activate
    $reset
}

pip_install() {
    # Send all output to stdout
    pip3 --disable-pip-version-check install "$@" 2>&1
}

upgrade_multiqc() {
    #Install/upgrade MultiQC from GIT
    #pip_install --upgrade --no-deps 'git+https://github.com/EdinburghGenomics/MultiQC.git@tim_branch#egg=multiqc'
    # For now, use the dev branch

    # For now we need specific older versions of these modules:
    pip_install 'networkx==1.11' 'spectra==0.0.8' 'colormath==2.1.1'

    for url in \
        'git+https://github.com/EdinburghGenomics/MultiQC.git@tim_branch#egg=multiqc' \
        'git+https://github.com/EdinburghGenomics/MultiQC_EdGen.git@master#egg=multiqc_edgen'
        do
        if [ "${1:-}" == 'initial' ] ; then
            pip_install "$url"
        else
            pip_install --upgrade --no-deps "$url"
        fi
    done

    # Quick check that it's (maybe) working:
    python -c "from multiqc.utils import config ; config.avail_modules['fastqc'].load()"
}

post_activate() {
    # If the toolbox has a post_activate_venv.sh then run it.
    _pav="${TOOLBOX:-`dirname $BASH_SOURCE`/toolbox}"/post_activate_venv.sh
    if [ -e "$_pav" ] ; then
        echo "Running commands in $_pav"
        source "$_pav"
    fi
}

if [ -e ./_illuminatus_venv/bin/activate ] ; then

    # We already got one!
    activate_venv

else
    (   _py3="${TOOLBOX:-`dirname $BASH_SOURCE`/toolbox}"/bootstrap_python3
        _py3_real="$(readlink -f "$_py3")"
        echo "Bootstrapping new VEnv from $_py3 ($_py3_real)"

        set -e
        "$_py3_real" -mvenv ./_illuminatus_venv
        activate_venv

        pip_install pip==19.2.1
        pip_install pyyaml==5.1.1
        pip_install yamlloader==0.5.5
        pip_install Rt==1.0.11
        pip_install pyclarity_lims==0.4.8
        pip_install psycopg2-binary==2.8.3
        pip_install pystache==0.5.4
        pip_install pyflakes==2.2.0

        # InterOP is now on PyPI so no pre-build needed :-)
        pip_install numpy==1.16.4
        pip_install interop==1.1.8

        # Needed if well_dups runs in the local VEnv, which it currently does.
        pip_install python-Levenshtein==0.12.0

        # snakemake and drmaa (note the settings/wrapper in shell_helper_functions.sh)
        pip_install snakemake==5.5.3
        pip_install drmaa==0.7.9

        # My own MultiQC and MultiQC_EdGen. Pip installs directly from GIT so
        # why not? Assume the master branch is always good, since it's simpler than
        # searching for the last release tag (though that is possible).
        # see https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support
        upgrade_multiqc initial

        post_activate
    )
    unset -f post_activate

    if [ $? = 0 ] ; then
        # We need this since we quit the subshell
        echo "VEnv provisioned OK"
        activate_venv
    else
        echo "Provisioning VEnv Failed!"
        false
    fi
fi
