#!/bin/bash

# Choose which well_duplicates to use and where to cache the cluster lists.

exec env PATH="/fluidfs/f1/from_lustre/software/well_duplicates/git_20171103:$PATH" \
         CLUSTER_LISTS="/fluidfs/f1/from_lustre/software/well_duplicates/shared_cluster_lists" \
         get_cached_targets.sh "$@"
