#!/bin/bash

# Choose which well_duplicates to use and where to cache the cluster lists.
BASE="/mnt/vdb"

exec env PATH="$BASE/software/well_duplicates/git_20180212:$PATH" \
         CLUSTER_LISTS="$BASE/software/well_duplicates/shared_cluster_lists" \
         get_cached_targets.sh "$@"
