# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python auto-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  auto_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: 'Set up Python 3.9'
      uses: actions/setup-python@main
      with:
        python-version: '3.9'
    - name: Set timezone
      uses: szenius/set-timezone@v1.1
      with:
        timezoneLinux: "Europe/London"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pyflakes
        pip install wheel
        pip install --prefer-binary -r test/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # also I'm fussy about some whitespace errors
        flake8 . --count --select=E9,F63,F7,F82,W191 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # disable some whitespace warnings as I do these deliberately
        flake8 . --count --ignore=E201,E202,E251 \
            --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with run_tests.sh
      run: |
        export RUN_NETWORK_TESTS=0
        ./test/run_tests.sh
